### ISSUE TITLE
IEML from Rules returns valid when given rules with 1 term

### ISSUE THREAD

**Issue by BigManWalter** [IEMLdev/ieml#38]
I sent the following rules to the API with the /usls/from_rules endpoint
{rules: {r0: "U:"}}

and it returned no errors, but when I go to save the word, it gives me: "This word must not be a term."

**Comment by ogrergo** [comment]
```python
str(usl({'r0': term('U:')}).ieml_object)
> '[([U:])]'
```

**Comment by Vayel** [comment]
It appear to have been fixed. Now, you can create any type of word from the endpoint `/words/`. Before, you could only create words not being term words.
